"""Voice-command scenario corpus: what a learner actually says, hands-free, in EN / Hinglish / Hindi.

Each case is (utterance as the browser recognizer would return it, expected intent, expected player
action or None). The action pins the slots end to end, so "go back half a minute" must be -30 s,
not merely SEEK_BACK. Used by tests/test_voice_corpus.py and scripts that replay it over /ws/session.

This is a regression suite and a seed set of base utterances for the Tier 1c classifier. It is NOT
an accuracy claim: the regex classifier was tuned against it. The honest metric stays the
real-speech test set (roadmap Tier 1c).

Labeling rules worth knowing (they also apply to Tier 1c data):
- Acknowledgements that end an exchange ("thanks", "got it", "theek hai") are STOP_SPEAKING (dismiss).
- "I didn't hear / catch that" is REPLAY; "I didn't understand / get it" is ASK.
- "I can't hear" (ongoing) is VOLUME up; "sunai nahi diya" (past) is REPLAY.
- "It's too fast" is SPEED down; "too loud" is VOLUME down (complaints invert the adjective).
- Undo / "go back to where I was", restart, go to the end/middle/N% are SEEK_ABSOLUTE.
- Questions that merely contain command words ("why did he go back?") are ASK, never a player action.
- "help" / "what can I say" is OOS (llm_router answers with the command list).
"""

from __future__ import annotations

from typing import Any

Action = dict[str, Any] | None


# ---------------------------------------------------------------- action helpers (the client contract)
def back(s: float, then: str | None = None) -> dict:
    return {"type": "SEEK_RELATIVE", "delta_s": -float(s), **({"then": then} if then else {})}


def fwd(s: float, then: str | None = None) -> dict:
    return {"type": "SEEK_RELATIVE", "delta_s": float(s), **({"then": then} if then else {})}


def to(s: float, then: str | None = None) -> dict:
    return {"type": "SEEK_TO", "seconds": float(s), **({"then": then} if then else {})}


def replay(s: float = 15) -> dict:
    return {"type": "SEEK_RELATIVE", "delta_s": -float(s), "then": "PLAY"}


def rate(r: float) -> dict:
    return {"type": "SET_RATE", "rate": r}


def frac(f: float) -> dict:
    return {"type": "SEEK_FRACTION", "fraction": f}


def vol(level: int) -> dict:
    return {"type": "VOLUME_SET", "level": level}


PLAY = {"type": "PLAY"}
PAUSE = {"type": "PAUSE"}
FASTER = {"type": "RATE_STEP", "delta": 0.25}
SLOWER = {"type": "RATE_STEP", "delta": -0.25}
LOUDER = {"type": "VOLUME_STEP", "delta": 20}
QUIETER = {"type": "VOLUME_STEP", "delta": -20}
MUTE = {"type": "MUTE"}
UNMUTE = {"type": "UNMUTE"}
STOP = {"type": "STOP_SPEAKING"}
START = to(0)
RESTART = to(0, "PLAY")
END = {"type": "SEEK_FRACTION", "fraction": 1.0, "offset_s": -30.0}
PREV = {"type": "SEEK_PREVIOUS"}

# ---------------------------------------------------------------- English (en-IN recognizer)
EN: list[tuple[str, str, Action]] = [
    # PLAY
    ("play", "PLAY", PLAY),
    ("resume", "PLAY", PLAY),
    ("continue", "PLAY", PLAY),
    ("go on", "PLAY", PLAY),
    ("keep going", "PLAY", PLAY),
    ("carry on", "PLAY", PLAY),
    ("start", "PLAY", PLAY),
    ("play the video", "PLAY", PLAY),
    ("resume playback", "PLAY", PLAY),
    ("unpause", "PLAY", PLAY),
    ("press play", "PLAY", PLAY),
    ("let's continue", "PLAY", PLAY),
    ("okay continue", "PLAY", PLAY),
    ("go ahead", "PLAY", PLAY),
    ("I'm back", "PLAY", PLAY),
    ("start again", "PLAY", PLAY),
    ("please play", "PLAY", PLAY),
    ("can you play the video", "PLAY", PLAY),
    ("could you please resume", "PLAY", PLAY),
    ("don't stop", "PLAY", PLAY),
    ("keep playing", "PLAY", PLAY),
    # PAUSE
    ("pause", "PAUSE", PAUSE),
    ("Pause.", "PAUSE", PAUSE),
    ("paws", "PAUSE", PAUSE),
    ("stop", "PAUSE", PAUSE),
    ("stop the video", "PAUSE", PAUSE),
    ("hold on", "PAUSE", PAUSE),
    ("hold it", "PAUSE", PAUSE),
    ("hang on", "PAUSE", PAUSE),
    ("wait", "PAUSE", PAUSE),
    ("wait a second", "PAUSE", PAUSE),
    ("one second", "PAUSE", PAUSE),
    ("one sec", "PAUSE", PAUSE),
    ("just a sec", "PAUSE", PAUSE),
    ("give me a minute", "PAUSE", PAUSE),
    ("freeze", "PAUSE", PAUSE),
    ("pause it", "PAUSE", PAUSE),
    ("pause the video please", "PAUSE", PAUSE),
    ("hit pause", "PAUSE", PAUSE),
    ("stop playing", "PAUSE", PAUSE),
    ("can you pause", "PAUSE", PAUSE),
    ("could you pause the video for a moment", "PAUSE", PAUSE),
    ("let's take a break", "PAUSE", PAUSE),
    # SEEK_BACK
    ("go back", "SEEK_BACK", back(10)),
    ("rewind", "SEEK_BACK", back(10)),
    ("back", "SEEK_BACK", back(10)),
    ("go back 10 seconds", "SEEK_BACK", back(10)),
    ("rewind 30 seconds", "SEEK_BACK", back(30)),
    ("back 5 seconds", "SEEK_BACK", back(5)),
    ("go back a bit", "SEEK_BACK", back(10)),
    ("go back a little", "SEEK_BACK", back(10)),
    ("jump back 20 seconds", "SEEK_BACK", back(20)),
    ("skip back 15 seconds", "SEEK_BACK", back(15)),
    ("go back one minute", "SEEK_BACK", back(60)),
    ("rewind a minute", "SEEK_BACK", back(60)),
    ("go back half a minute", "SEEK_BACK", back(30)),
    ("go back a minute and a half", "SEEK_BACK", back(90)),
    ("go back one and a half minutes", "SEEK_BACK", back(90)),
    ("go back 1 minute 30 seconds", "SEEK_BACK", back(90)),
    ("rewind 2 mins", "SEEK_BACK", back(120)),
    ("go back forty five seconds", "SEEK_BACK", back(45)),
    ("go back thirty seconds", "SEEK_BACK", back(30)),
    ("10 seconds back", "SEEK_BACK", back(10)),
    ("back by 20 seconds", "SEEK_BACK", back(20)),
    ("rewind by 10 sec", "SEEK_BACK", back(10)),
    ("go back a few seconds", "SEEK_BACK", back(5)),
    ("go back a couple of seconds", "SEEK_BACK", back(2)),
    ("go back a lot", "SEEK_BACK", back(30)),
    ("way back", "SEEK_BACK", back(30)),
    ("can you go back 10 seconds", "SEEK_BACK", back(10)),
    ("go back 30 seconds and play", "SEEK_BACK", back(30, "PLAY")),
    ("go back 10 seconds and pause", "SEEK_BACK", back(10, "PAUSE")),
    ("pause and go back 10 seconds", "SEEK_BACK", back(10, "PAUSE")),
    # SEEK_FORWARD
    ("skip", "SEEK_FORWARD", fwd(10)),
    ("forward", "SEEK_FORWARD", fwd(10)),
    ("fast forward", "SEEK_FORWARD", fwd(10)),
    ("skip ahead", "SEEK_FORWARD", fwd(10)),
    ("go forward", "SEEK_FORWARD", fwd(10)),
    ("skip 10 seconds", "SEEK_FORWARD", fwd(10)),
    ("skip ten seconds", "SEEK_FORWARD", fwd(10)),
    ("jump ahead 30 seconds", "SEEK_FORWARD", fwd(30)),
    ("forward a minute", "SEEK_FORWARD", fwd(60)),
    ("skip a minute", "SEEK_FORWARD", fwd(60)),
    ("fast forward 2 minutes", "SEEK_FORWARD", fwd(120)),
    ("go ahead 20 seconds", "SEEK_FORWARD", fwd(20)),
    ("move ahead 15 seconds", "SEEK_FORWARD", fwd(15)),
    ("skip forty five seconds", "SEEK_FORWARD", fwd(45)),
    ("skip a few seconds", "SEEK_FORWARD", fwd(5)),
    ("skip this part", "SEEK_FORWARD", fwd(30)),
    ("skip ahead a lot", "SEEK_FORWARD", fwd(30)),
    ("skip 30 seconds and play", "SEEK_FORWARD", fwd(30, "PLAY")),
    # SEEK_ABSOLUTE
    ("go to 12:30", "SEEK_ABSOLUTE", to(750)),
    ("jump to 5:00", "SEEK_ABSOLUTE", to(300)),
    ("go to 1:05:20", "SEEK_ABSOLUTE", to(3920)),
    ("go to minute 12", "SEEK_ABSOLUTE", to(720)),
    ("go to 12 minutes", "SEEK_ABSOLUTE", to(720)),
    ("jump to 5 minutes 30 seconds", "SEEK_ABSOLUTE", to(330)),
    ("go to 12 30", "SEEK_ABSOLUTE", to(750)),
    ("go to 1230", "SEEK_ABSOLUTE", to(750)),
    ("go to twelve thirty", "SEEK_ABSOLUTE", to(750)),
    ("go to 12", "SEEK_ABSOLUTE", to(720)),
    ("take me to 45:10", "SEEK_ABSOLUTE", to(2710)),
    ("play from 3:40", "SEEK_ABSOLUTE", to(220, "PLAY")),
    ("start from 10:00", "SEEK_ABSOLUTE", to(600, "PLAY")),
    ("go to 12:30 and pause", "SEEK_ABSOLUTE", to(750, "PAUSE")),
    ("go to the beginning", "SEEK_ABSOLUTE", START),
    ("go to the start", "SEEK_ABSOLUTE", START),
    ("back to the start", "SEEK_ABSOLUTE", START),
    ("restart", "SEEK_ABSOLUTE", RESTART),
    ("restart the video", "SEEK_ABSOLUTE", RESTART),
    ("start over", "SEEK_ABSOLUTE", RESTART),
    ("start from the beginning", "SEEK_ABSOLUTE", RESTART),
    ("play from the beginning", "SEEK_ABSOLUTE", RESTART),
    ("from the top", "SEEK_ABSOLUTE", RESTART),
    ("go to the end", "SEEK_ABSOLUTE", END),
    ("skip to the end", "SEEK_ABSOLUTE", END),
    ("go to the middle", "SEEK_ABSOLUTE", frac(0.5)),
    ("jump halfway", "SEEK_ABSOLUTE", frac(0.5)),
    ("go to 50 percent", "SEEK_ABSOLUTE", frac(0.5)),
    ("skip to 75%", "SEEK_ABSOLUTE", frac(0.75)),
    ("undo", "SEEK_ABSOLUTE", PREV),
    ("go back to where I was", "SEEK_ABSOLUTE", PREV),
    ("take me back to where I was", "SEEK_ABSOLUTE", PREV),
    # REPLAY
    ("say that again", "REPLAY", replay()),
    ("repeat", "REPLAY", replay()),
    ("repeat that", "REPLAY", replay()),
    ("replay", "REPLAY", replay()),
    ("play that again", "REPLAY", replay()),
    ("once more", "REPLAY", replay()),
    ("one more time", "REPLAY", replay()),
    ("come again", "REPLAY", replay()),
    ("what did he say", "REPLAY", replay()),
    ("what was that", "REPLAY", replay()),
    ("I missed that", "REPLAY", replay()),
    ("I didn't hear that", "REPLAY", replay()),
    ("didn't catch that", "REPLAY", replay()),
    ("sorry what", "REPLAY", replay()),
    ("pardon", "REPLAY", replay()),
    ("rewind and play", "REPLAY", replay()),
    ("repeat the last 30 seconds", "REPLAY", replay(30)),
    ("replay the last minute", "REPLAY", replay(60)),
    # SPEED
    ("faster", "SPEED", FASTER),
    ("speed up", "SPEED", FASTER),
    ("play faster", "SPEED", FASTER),
    ("increase speed", "SPEED", FASTER),
    ("a bit faster", "SPEED", FASTER),
    ("too slow", "SPEED", FASTER),
    ("slower", "SPEED", SLOWER),
    ("slow down", "SPEED", SLOWER),
    ("decrease the speed", "SPEED", SLOWER),
    ("it's too fast", "SPEED", SLOWER),
    ("he's speaking too fast", "SPEED", SLOWER),
    ("normal speed", "SPEED", rate(1.0)),
    ("reset speed", "SPEED", rate(1.0)),
    ("back to normal speed", "SPEED", rate(1.0)),
    ("1.5x", "SPEED", rate(1.5)),
    ("speed 1.5", "SPEED", rate(1.5)),
    ("1.5 speed", "SPEED", rate(1.5)),
    ("set speed to 1.25", "SPEED", rate(1.25)),
    ("play at 1.75x", "SPEED", rate(1.75)),
    ("play at 2x", "SPEED", rate(2.0)),
    ("double speed", "SPEED", rate(2.0)),
    ("twice the speed", "SPEED", rate(2.0)),
    ("half speed", "SPEED", rate(0.5)),
    ("max speed", "SPEED", rate(2.0)),
    ("fastest", "SPEED", rate(2.0)),
    ("slowest", "SPEED", rate(0.25)),
    ("speed one point five", "SPEED", rate(1.5)),
    ("speed 1 point 25", "SPEED", rate(1.25)),
    ("one and a half speed", "SPEED", rate(1.5)),
    # VOLUME
    ("mute", "VOLUME", MUTE),
    ("mute the video", "VOLUME", MUTE),
    ("sound off", "VOLUME", MUTE),
    ("turn off the sound", "VOLUME", MUTE),
    ("put it on mute", "VOLUME", MUTE),
    ("unmute", "VOLUME", UNMUTE),
    ("on mute", "VOLUME", UNMUTE),
    ("sound on", "VOLUME", UNMUTE),
    ("turn the sound back on", "VOLUME", UNMUTE),
    ("louder", "VOLUME", LOUDER),
    ("volume up", "VOLUME", LOUDER),
    ("turn it up", "VOLUME", LOUDER),
    ("increase the volume", "VOLUME", LOUDER),
    ("a bit louder", "VOLUME", LOUDER),
    ("I can't hear", "VOLUME", LOUDER),
    ("I can't hear anything", "VOLUME", LOUDER),
    ("quieter", "VOLUME", QUIETER),
    ("softer", "VOLUME", QUIETER),
    ("volume down", "VOLUME", QUIETER),
    ("turn it down", "VOLUME", QUIETER),
    ("lower the volume", "VOLUME", QUIETER),
    ("too loud", "VOLUME", QUIETER),
    ("full volume", "VOLUME", vol(100)),
    ("max volume", "VOLUME", vol(100)),
    ("volume 50", "VOLUME", vol(50)),
    ("set volume to 30 percent", "VOLUME", vol(30)),
    ("half volume", "VOLUME", vol(50)),
    # STOP_SPEAKING (dismiss)
    ("stop talking", "STOP_SPEAKING", STOP),
    ("stop speaking", "STOP_SPEAKING", STOP),
    ("be quiet", "STOP_SPEAKING", STOP),
    ("quiet", "STOP_SPEAKING", STOP),
    ("shut up", "STOP_SPEAKING", STOP),
    ("enough", "STOP_SPEAKING", STOP),
    ("that's enough", "STOP_SPEAKING", STOP),
    ("cancel", "STOP_SPEAKING", STOP),
    ("never mind", "STOP_SPEAKING", STOP),
    ("forget it", "STOP_SPEAKING", STOP),
    ("thanks", "STOP_SPEAKING", STOP),
    ("thank you", "STOP_SPEAKING", STOP),
    ("okay", "STOP_SPEAKING", STOP),
    ("got it", "STOP_SPEAKING", STOP),
    ("okay got it", "STOP_SPEAKING", STOP),
    ("understood", "STOP_SPEAKING", STOP),
    ("alright", "STOP_SPEAKING", STOP),
    ("sounds good", "STOP_SPEAKING", STOP),
]

# ---------------------------------------------------------------- Hinglish in Latin script
# (Hindi spoken with the EN toggle → en-IN recognizer; spellings vary, so variants are included)
HINGLISH: list[tuple[str, str, Action]] = [
    # PLAY
    ("chalao", "PLAY", PLAY),
    ("video chalao", "PLAY", PLAY),
    ("chala do", "PLAY", PLAY),
    ("chalu karo", "PLAY", PLAY),
    ("play karo", "PLAY", PLAY),
    ("resume karo", "PLAY", PLAY),
    ("shuru karo", "PLAY", PLAY),
    ("chalne do", "PLAY", PLAY),
    ("aage chalao", "PLAY", PLAY),
    ("continue karo", "PLAY", PLAY),
    ("zara chalao", "PLAY", PLAY),
    ("ruko mat", "PLAY", PLAY),
    ("mat roko", "PLAY", PLAY),
    ("main aa gaya", "PLAY", PLAY),
    # PAUSE
    ("ruko", "PAUSE", PAUSE),
    ("ruk jao", "PAUSE", PAUSE),
    ("roko", "PAUSE", PAUSE),
    ("rok do", "PAUSE", PAUSE),
    ("video roko", "PAUSE", PAUSE),
    ("pause karo", "PAUSE", PAUSE),
    ("pause kar do", "PAUSE", PAUSE),
    ("thehro", "PAUSE", PAUSE),
    ("zara ruko", "PAUSE", PAUSE),
    ("ek minute ruko", "PAUSE", PAUSE),
    ("ek second", "PAUSE", PAUSE),
    ("ek minute", "PAUSE", PAUSE),
    ("band karo", "PAUSE", PAUSE),
    ("video band karo", "PAUSE", PAUSE),
    ("rukiye", "PAUSE", PAUSE),
    ("kya aap video rok sakte hain", "PAUSE", PAUSE),
    # SEEK_BACK
    ("peeche jao", "SEEK_BACK", back(10)),
    ("thoda peeche", "SEEK_BACK", back(10)),
    ("thoda peeche jao", "SEEK_BACK", back(10)),
    ("piche jao", "SEEK_BACK", back(10)),
    ("10 second peeche", "SEEK_BACK", back(10)),
    ("das second peeche jao", "SEEK_BACK", back(10)),
    ("ek minute peeche", "SEEK_BACK", back(60)),
    ("do minute peeche", "SEEK_BACK", back(120)),
    ("aadha minute peeche", "SEEK_BACK", back(30)),
    ("dedh minute peeche", "SEEK_BACK", back(90)),
    ("30 second peeche karo", "SEEK_BACK", back(30)),
    ("pichhe 20 second", "SEEK_BACK", back(20)),
    ("paintalis second peeche", "SEEK_BACK", back(45)),
    ("peeche karo", "SEEK_BACK", back(10)),
    ("rewind karo", "SEEK_BACK", back(10)),
    ("back karo", "SEEK_BACK", back(10)),
    ("thoda aur peeche", "SEEK_BACK", back(10)),
    ("bahut peeche jao", "SEEK_BACK", back(30)),
    ("wapas jao", "SEEK_BACK", back(10)),
    ("peeche jao aur chalao", "SEEK_BACK", back(10, "PLAY")),
    # SEEK_FORWARD
    ("aage jao", "SEEK_FORWARD", fwd(10)),
    ("aage karo", "SEEK_FORWARD", fwd(10)),
    ("aage badhao", "SEEK_FORWARD", fwd(10)),
    ("aagey jao", "SEEK_FORWARD", fwd(10)),
    ("thoda aage", "SEEK_FORWARD", fwd(10)),
    ("thoda aur aage", "SEEK_FORWARD", fwd(10)),
    ("10 second aage", "SEEK_FORWARD", fwd(10)),
    ("das second aage karo", "SEEK_FORWARD", fwd(10)),
    ("ek minute aage", "SEEK_FORWARD", fwd(60)),
    ("do minute aage", "SEEK_FORWARD", fwd(120)),
    ("teen minute aage badhao", "SEEK_FORWARD", fwd(180)),
    ("skip karo", "SEEK_FORWARD", fwd(10)),
    ("forward karo", "SEEK_FORWARD", fwd(10)),
    ("aage skip karo", "SEEK_FORWARD", fwd(10)),
    ("bahut aage jao", "SEEK_FORWARD", fwd(30)),
    # SEEK_ABSOLUTE
    ("12:30 pe jao", "SEEK_ABSOLUTE", to(750)),
    ("12:30 par le chalo", "SEEK_ABSOLUTE", to(750)),
    ("5 minute pe jao", "SEEK_ABSOLUTE", to(300)),
    ("12 minute 30 second pe jao", "SEEK_ABSOLUTE", to(750)),
    ("baarah tees pe jao", "SEEK_ABSOLUTE", to(750)),
    ("5 minute se chalao", "SEEK_ABSOLUTE", to(300, "PLAY")),
    ("shuru se chalao", "SEEK_ABSOLUTE", RESTART),
    ("shuruaat se dikhao", "SEEK_ABSOLUTE", RESTART),
    ("dobara shuru karo", "SEEK_ABSOLUTE", RESTART),
    ("phir se shuru karo", "SEEK_ABSOLUTE", RESTART),
    ("restart karo", "SEEK_ABSOLUTE", RESTART),
    ("end pe jao", "SEEK_ABSOLUTE", END),
    ("aakhir mein jao", "SEEK_ABSOLUTE", END),
    ("video ke beech mein jao", "SEEK_ABSOLUTE", frac(0.5)),
    ("aadhe video pe jao", "SEEK_ABSOLUTE", frac(0.5)),
    ("50 percent pe jao", "SEEK_ABSOLUTE", frac(0.5)),
    ("wapas wahin jao", "SEEK_ABSOLUTE", PREV),
    ("jahan tha wahan le chalo", "SEEK_ABSOLUTE", PREV),
    ("undo karo", "SEEK_ABSOLUTE", PREV),
    # REPLAY
    ("phir se dikhao", "REPLAY", replay()),
    ("fir se dikhao", "REPLAY", replay()),
    ("phir se sunao", "REPLAY", replay()),
    ("phir se chalao", "REPLAY", replay()),
    ("dobara sunao", "REPLAY", replay()),
    ("dobara dikhao", "REPLAY", replay()),
    ("ek baar aur", "REPLAY", replay()),
    ("ek baar phir", "REPLAY", replay()),
    ("repeat karo", "REPLAY", replay()),
    ("replay karo", "REPLAY", replay()),
    ("kya bola", "REPLAY", replay()),
    ("kya kaha", "REPLAY", replay()),
    ("sunai nahi diya", "REPLAY", replay()),
    ("pichhle 30 second phir se", "REPLAY", replay(30)),
    ("last minute phir se dikhao", "REPLAY", replay(60)),
    # SPEED
    ("tez karo", "SPEED", FASTER),
    ("thoda tez karo", "SPEED", FASTER),
    ("speed badhao", "SPEED", FASTER),
    ("fast karo", "SPEED", FASTER),
    ("bahut dheere hai", "SPEED", FASTER),
    ("speed kam karo", "SPEED", SLOWER),
    ("dheere karo", "SPEED", SLOWER),
    ("dheere chalao", "SPEED", SLOWER),
    ("slow karo", "SPEED", SLOWER),
    ("bahut tez bol raha hai", "SPEED", SLOWER),
    ("normal speed karo", "SPEED", rate(1.0)),
    ("speed normal karo", "SPEED", rate(1.0)),
    ("speed dedh karo", "SPEED", rate(1.5)),
    ("speed 1.5 karo", "SPEED", rate(1.5)),
    ("speed do guna karo", "SPEED", rate(2.0)),
    ("double speed karo", "SPEED", rate(2.0)),
    ("aadhi speed", "SPEED", rate(0.5)),
    ("sava speed", "SPEED", rate(1.25)),
    ("speed paune do karo", "SPEED", rate(1.75)),
    # VOLUME
    ("awaaz badhao", "VOLUME", LOUDER),
    ("awaaz tez karo", "VOLUME", LOUDER),
    ("volume badhao", "VOLUME", LOUDER),
    ("awaaz nahi aa rahi", "VOLUME", LOUDER),
    ("sunai nahi de raha", "VOLUME", LOUDER),
    ("awaz kam hai", "VOLUME", LOUDER),
    ("awaaz kam karo", "VOLUME", QUIETER),
    ("awaaz dheere karo", "VOLUME", QUIETER),
    ("volume kam karo", "VOLUME", QUIETER),
    ("awaaz bahut tez hai", "VOLUME", QUIETER),
    ("awaaz band karo", "VOLUME", MUTE),
    ("mute karo", "VOLUME", MUTE),
    ("silent karo", "VOLUME", MUTE),
    ("awaaz chalu karo", "VOLUME", UNMUTE),
    ("awaaz wapas lao", "VOLUME", UNMUTE),
    ("unmute karo", "VOLUME", UNMUTE),
    ("volume full karo", "VOLUME", vol(100)),
    ("awaaz poori karo", "VOLUME", vol(100)),
    ("awaaz aadhi karo", "VOLUME", vol(50)),
    ("volume 50 karo", "VOLUME", vol(50)),
    # STOP_SPEAKING (dismiss)
    ("bas", "STOP_SPEAKING", STOP),
    ("bas karo", "STOP_SPEAKING", STOP),
    ("bas bas", "STOP_SPEAKING", STOP),
    ("chup", "STOP_SPEAKING", STOP),
    ("chup ho jao", "STOP_SPEAKING", STOP),
    ("chup raho", "STOP_SPEAKING", STOP),
    ("rehne do", "STOP_SPEAKING", STOP),
    ("chhodo", "STOP_SPEAKING", STOP),
    ("koi baat nahi", "STOP_SPEAKING", STOP),
    ("kuch nahi", "STOP_SPEAKING", STOP),
    ("theek hai", "STOP_SPEAKING", STOP),
    ("achha theek hai", "STOP_SPEAKING", STOP),
    ("samajh gaya", "STOP_SPEAKING", STOP),
    ("shukriya", "STOP_SPEAKING", STOP),
    ("dhanyavaad", "STOP_SPEAKING", STOP),
]

# ---------------------------------------------------------------- Hindi as Chrome hi-IN returns it (Devanagari)
HINDI: list[tuple[str, str, Action]] = [
    # PLAY
    ("चलाओ", "PLAY", PLAY),
    ("वीडियो चलाओ", "PLAY", PLAY),
    ("चला दो", "PLAY", PLAY),
    ("चालू करो", "PLAY", PLAY),
    ("प्ले करो", "PLAY", PLAY),
    ("शुरू करो", "PLAY", PLAY),
    ("चलने दो", "PLAY", PLAY),
    ("जारी रखो", "PLAY", PLAY),
    ("रिज्यूम करो", "PLAY", PLAY),
    ("कंटिन्यू करो", "PLAY", PLAY),
    ("रुको मत", "PLAY", PLAY),
    # PAUSE
    ("रुको", "PAUSE", PAUSE),
    ("रूको", "PAUSE", PAUSE),
    ("रुक जाओ", "PAUSE", PAUSE),
    ("रोको", "PAUSE", PAUSE),
    ("रोक दो", "PAUSE", PAUSE),
    ("ठहरो", "PAUSE", PAUSE),
    ("पॉज़ करो", "PAUSE", PAUSE),
    ("वीडियो रोको", "PAUSE", PAUSE),
    ("ज़रा रुको", "PAUSE", PAUSE),
    ("एक मिनट", "PAUSE", PAUSE),
    ("बंद करो", "PAUSE", PAUSE),
    ("क्या आप वीडियो रोक सकते हैं", "PAUSE", PAUSE),
    # SEEK_BACK
    ("पीछे जाओ", "SEEK_BACK", back(10)),
    ("थोड़ा पीछे जाओ", "SEEK_BACK", back(10)),
    ("दस सेकंड पीछे", "SEEK_BACK", back(10)),
    ("10 सेकंड पीछे जाओ", "SEEK_BACK", back(10)),
    ("एक मिनट पीछे", "SEEK_BACK", back(60)),
    ("आधा मिनट पीछे", "SEEK_BACK", back(30)),
    ("डेढ़ मिनट पीछे जाओ", "SEEK_BACK", back(90)),
    ("पैंतालीस सेकंड पीछे", "SEEK_BACK", back(45)),
    ("रिवाइंड करो", "SEEK_BACK", back(10)),
    ("बैक करो", "SEEK_BACK", back(10)),
    ("थोड़ा और पीछे", "SEEK_BACK", back(10)),
    ("बहुत पीछे जाओ", "SEEK_BACK", back(30)),
    ("वापस जाओ", "SEEK_BACK", back(10)),
    ("गो बैक 10 सेकंड", "SEEK_BACK", back(10)),
    # SEEK_FORWARD
    ("आगे जाओ", "SEEK_FORWARD", fwd(10)),
    ("आगे बढ़ाओ", "SEEK_FORWARD", fwd(10)),
    ("थोड़ा आगे करो", "SEEK_FORWARD", fwd(10)),
    ("दस सेकंड आगे करो", "SEEK_FORWARD", fwd(10)),
    ("बीस सेकंड आगे", "SEEK_FORWARD", fwd(20)),
    ("एक मिनट आगे", "SEEK_FORWARD", fwd(60)),
    ("दो मिनट आगे जाओ", "SEEK_FORWARD", fwd(120)),
    ("स्किप करो", "SEEK_FORWARD", fwd(10)),
    ("फॉरवर्ड करो", "SEEK_FORWARD", fwd(10)),
    # SEEK_ABSOLUTE
    ("12:30 पर जाओ", "SEEK_ABSOLUTE", to(750)),
    ("बारह तीस पर जाओ", "SEEK_ABSOLUTE", to(750)),
    ("पाँच मिनट पर जाओ", "SEEK_ABSOLUTE", to(300)),
    ("बारह मिनट तीस सेकंड पर जाओ", "SEEK_ABSOLUTE", to(750)),
    ("शुरू से चलाओ", "SEEK_ABSOLUTE", RESTART),
    ("शुरुआत से दिखाओ", "SEEK_ABSOLUTE", RESTART),
    ("फिर से शुरू करो", "SEEK_ABSOLUTE", RESTART),
    ("रीस्टार्ट करो", "SEEK_ABSOLUTE", RESTART),
    ("आख़िर में जाओ", "SEEK_ABSOLUTE", END),
    ("बीच में जाओ", "SEEK_ABSOLUTE", frac(0.5)),
    ("पचास प्रतिशत पर जाओ", "SEEK_ABSOLUTE", frac(0.5)),
    ("वापस वहीं जाओ", "SEEK_ABSOLUTE", PREV),
    # REPLAY
    ("फिर से दिखाओ", "REPLAY", replay()),
    ("फिर से सुनाओ", "REPLAY", replay()),
    ("दोबारा सुनाओ", "REPLAY", replay()),
    ("एक बार और", "REPLAY", replay()),
    ("रिपीट करो", "REPLAY", replay()),
    ("रिप्ले करो", "REPLAY", replay()),
    ("क्या बोला", "REPLAY", replay()),
    ("क्या कहा", "REPLAY", replay()),
    ("सुनाई नहीं दिया", "REPLAY", replay()),
    # SPEED
    ("तेज़ करो", "SPEED", FASTER),
    ("स्पीड बढ़ाओ", "SPEED", FASTER),
    ("स्पीड कम करो", "SPEED", SLOWER),
    ("धीरे करो", "SPEED", SLOWER),
    ("धीमा करो", "SPEED", SLOWER),
    ("धीरे चलाओ", "SPEED", SLOWER),
    ("बहुत तेज़ बोल रहा है", "SPEED", SLOWER),
    ("नॉर्मल स्पीड", "SPEED", rate(1.0)),
    ("स्पीड डेढ़ कर दो", "SPEED", rate(1.5)),
    ("स्पीड 1.5 कर दो", "SPEED", rate(1.5)),
    ("डबल स्पीड", "SPEED", rate(2.0)),
    ("दुगनी स्पीड करो", "SPEED", rate(2.0)),
    # VOLUME
    ("आवाज़ बढ़ाओ", "VOLUME", LOUDER),
    ("वॉल्यूम बढ़ाओ", "VOLUME", LOUDER),
    ("आवाज़ नहीं आ रही", "VOLUME", LOUDER),
    ("सुनाई नहीं दे रहा", "VOLUME", LOUDER),
    ("आवाज़ कम करो", "VOLUME", QUIETER),
    ("आवाज़ धीमी करो", "VOLUME", QUIETER),
    ("आवाज़ बंद करो", "VOLUME", MUTE),
    ("म्यूट करो", "VOLUME", MUTE),
    ("आवाज़ चालू करो", "VOLUME", UNMUTE),
    ("अनम्यूट करो", "VOLUME", UNMUTE),
    ("आवाज़ पूरी करो", "VOLUME", vol(100)),
    # STOP_SPEAKING (dismiss)
    ("बस", "STOP_SPEAKING", STOP),
    ("बस करो", "STOP_SPEAKING", STOP),
    ("चुप", "STOP_SPEAKING", STOP),
    ("चुप हो जाओ", "STOP_SPEAKING", STOP),
    ("रहने दो", "STOP_SPEAKING", STOP),
    ("छोड़ो", "STOP_SPEAKING", STOP),
    ("ठीक है", "STOP_SPEAKING", STOP),
    ("समझ गया", "STOP_SPEAKING", STOP),
    ("धन्यवाद", "STOP_SPEAKING", STOP),
    ("शुक्रिया", "STOP_SPEAKING", STOP),
]

# ---------------------------------------------------------------- slow path: routed correctly (answers arrive in Tier 1b/1e)
SLOW_PATH: list[tuple[str, str, Action]] = [
    # ASK
    ("what is gradient descent", "ASK", None),
    ("why do we square the error", "ASK", None),
    ("how does backpropagation work", "ASK", None),
    ("explain this", "ASK", None),
    ("can you explain that again", "ASK", None),
    ("I don't understand", "ASK", None),
    ("I didn't get that", "ASK", None),
    ("what does this mean", "ASK", None),
    ("define entropy", "ASK", None),
    ("tell me more about this", "ASK", None),
    ("give me an example", "ASK", None),
    ("what's the difference between a list and an array", "ASK", None),
    ("is this important for the exam", "ASK", None),
    ("help me understand this", "ASK", None),
    ("ye kya hai", "ASK", None),
    ("iska matlab kya hai", "ASK", None),
    ("samjhao", "ASK", None),
    ("samjha do", "ASK", None),
    ("explain karo", "ASK", None),
    ("ye kyun hota hai", "ASK", None),
    ("ye kaise kaam karta hai", "ASK", None),
    ("samajh nahi aaya", "ASK", None),
    ("phir se samjhao", "ASK", None),
    ("example do", "ASK", None),
    ("gradient descent kya hota hai", "ASK", None),
    ("ये क्या है", "ASK", None),
    ("इसका मतलब क्या है", "ASK", None),
    ("समझाओ", "ASK", None),
    ("समझ नहीं आया", "ASK", None),
    ("ये क्यों होता है", "ASK", None),
    ("फिर से समझाओ", "ASK", None),
    ("उदाहरण दो", "ASK", None),
    ("मुझे समझाओ", "ASK", None),
    # SUMMARIZE
    ("summarize", "SUMMARIZE", None),
    ("summarize so far", "SUMMARIZE", None),
    ("give me a summary", "SUMMARIZE", None),
    ("recap", "SUMMARIZE", None),
    ("what have we covered", "SUMMARIZE", None),
    ("what did I miss", "SUMMARIZE", None),
    ("key points please", "SUMMARIZE", None),
    ("sum it up", "SUMMARIZE", None),
    ("summary do", "SUMMARIZE", None),
    ("ab tak kya hua", "SUMMARIZE", None),
    ("short mein batao", "SUMMARIZE", None),
    ("सारांश बताओ", "SUMMARIZE", None),
    ("अब तक क्या हुआ", "SUMMARIZE", None),
    ("समरी दो", "SUMMARIZE", None),
    # TAKE_NOTE
    ("note this down", "TAKE_NOTE", None),
    ("take a note", "TAKE_NOTE", None),
    ("make a note", "TAKE_NOTE", None),
    ("write this down", "TAKE_NOTE", None),
    ("save this", "TAKE_NOTE", None),
    ("bookmark this", "TAKE_NOTE", None),
    ("remember this", "TAKE_NOTE", None),
    ("mark this point", "TAKE_NOTE", None),
    ("note that the complexity is n log n", "TAKE_NOTE", None),
    ("note karo", "TAKE_NOTE", None),
    ("ye note kar lo", "TAKE_NOTE", None),
    ("likh lo", "TAKE_NOTE", None),
    ("bookmark karo", "TAKE_NOTE", None),
    ("yaad rakhna", "TAKE_NOTE", None),
    ("नोट करो", "TAKE_NOTE", None),
    ("ये नोट कर लो", "TAKE_NOTE", None),
    ("लिख लो", "TAKE_NOTE", None),
    ("बुकमार्क करो", "TAKE_NOTE", None),
    ("याद रखना", "TAKE_NOTE", None),
    # SEMANTIC_SEEK
    ("skip to the part about complexity", "SEMANTIC_SEEK", None),
    ("go to where he explains recursion", "SEMANTIC_SEEK", None),
    ("jump to backpropagation", "SEMANTIC_SEEK", None),
    ("take me to the example", "SEMANTIC_SEEK", None),
    ("go back to the example", "SEMANTIC_SEEK", None),
    ("find the part about sorting", "SEMANTIC_SEEK", None),
    ("where does he talk about hashing", "SEMANTIC_SEEK", None),
    ("skip the intro", "SEMANTIC_SEEK", None),
    ("search for binary search", "SEMANTIC_SEEK", None),
    ("go to the conclusion", "SEMANTIC_SEEK", None),
    ("gradient descent wala part dikhao", "SEMANTIC_SEEK", None),
    ("recursion pe jao", "SEMANTIC_SEEK", None),
    ("backprop kahan explain kiya hai", "SEMANTIC_SEEK", None),
    ("sorting wale hisse pe le chalo", "SEMANTIC_SEEK", None),
    ("जहाँ recursion समझाया है वहाँ जाओ", "SEMANTIC_SEEK", None),
    ("sorting वाला पार्ट दिखाओ", "SEMANTIC_SEEK", None),
    # OOS (help is answered by llm_router with the command list)
    ("hello", "OOS", None),
    ("the weather is nice", "OOS", None),
    ("I like this lecture", "OOS", None),
    ("help", "OOS", None),
    ("what can I say", "OOS", None),
    ("kya kya bol sakta hoon", "OOS", None),
    ("madad", "OOS", None),
]

# ---------------------------------------------------------------- precision: command words inside questions / negations
# A wrong jump or pause mid-lecture is worse than "didn't catch that", so these must NOT act.
PRECISION: list[tuple[str, str, Action]] = [
    ("why did he go back to the previous slide", "ASK", None),
    ("what does pause mean in music", "ASK", None),
    ("how do I speed up gradient descent", "ASK", None),
    ("what is the volume of a sphere", "ASK", None),
    ("is merge sort faster than quick sort", "ASK", None),
    ("which algorithm is slower", "ASK", None),
    ("why is the learning rate important", "ASK", None),
    ("can you explain why we go back", "ASK", None),
    ("what happens if we skip normalization", "ASK", None),
    ("tell me about the next part", "ASK", None),
    ("wo peeche kyun gaya", "ASK", None),
    ("ye algorithm tez kyun hai", "ASK", None),
    ("awaaz kaise badhate hain", "ASK", None),
    ("speed of light kya hai", "ASK", None),
    ("वो पीछे क्यों गया", "ASK", None),
    ("don't skip", "OOS", None),
    ("don't mute", "OOS", None),
    ("mat skip karo", "OOS", None),
    ("don't pause", "PLAY", PLAY),
]

# ---------------------------------------------------------------- held-out rounds (19 Sep 2026)
# Written AFTER the rules above and scored once before any fix: round 1 = 70/95 (74%), round 2 = 64/70
# (91%, the honest generalization estimate for the regex classifier). Misses were fixed by general
# rules (word order, intent frames, chained acknowledgements), then the phrases were kept as regressions.
HELDOUT: list[tuple[str, str, Action]] = [
    # round 1
    ("pause for a sec", "PAUSE", PAUSE),
    ("stop it", "PAUSE", PAUSE),
    ("hold up", "PAUSE", PAUSE),
    ("wait wait", "PAUSE", PAUSE),
    ("resume the lecture", "PLAY", PLAY),
    ("okay let's go", "PLAY", PLAY),
    ("keep it going", "PLAY", PLAY),
    ("rewind a bit", "SEEK_BACK", back(10)),
    ("go back five seconds", "SEEK_BACK", back(5)),
    ("back up 15 seconds", "SEEK_BACK", back(15)),
    ("jump back a minute", "SEEK_BACK", back(60)),
    ("rewind fifteen seconds", "SEEK_BACK", back(15)),
    ("go back like 20 seconds", "SEEK_BACK", back(20)),
    ("can you rewind 10 seconds please", "SEEK_BACK", back(10)),
    ("take it back 30 seconds", "SEEK_BACK", back(30)),
    ("take me back", "SEEK_BACK", back(10)),
    ("skip forward 20 seconds", "SEEK_FORWARD", fwd(20)),
    ("jump forward a bit", "SEEK_FORWARD", fwd(10)),
    ("move forward one minute", "SEEK_FORWARD", fwd(60)),
    ("fast forward thirty seconds", "SEEK_FORWARD", fwd(30)),
    ("skip two minutes", "SEEK_FORWARD", fwd(120)),
    ("skip ahead ninety seconds", "SEEK_FORWARD", fwd(90)),
    ("I want to skip this part", "SEEK_FORWARD", fwd(30)),
    ("jump to 7:45", "SEEK_ABSOLUTE", to(465)),
    ("go to minute 3", "SEEK_ABSOLUTE", to(180)),
    ("seek to 2:10", "SEEK_ABSOLUTE", to(130)),
    ("go to the 10 minute mark", "SEEK_ABSOLUTE", to(600)),
    ("rewind to the beginning", "SEEK_ABSOLUTE", START),
    ("I want to go back to the start", "SEEK_ABSOLUTE", START),
    ("take me to the end", "SEEK_ABSOLUTE", END),
    ("go to the halfway point", "SEEK_ABSOLUTE", frac(0.5)),
    ("jump to 25 percent", "SEEK_ABSOLUTE", frac(0.25)),
    ("undo that", "SEEK_ABSOLUTE", PREV),
    ("start the video over", "SEEK_ABSOLUTE", RESTART),
    ("say it again", "REPLAY", replay()),
    ("what did he just say", "REPLAY", replay()),
    ("I didn't catch what he said", "REPLAY", replay()),
    ("play that part again", "REPLAY", replay()),
    ("can you replay the last 10 seconds", "REPLAY", replay(10)),
    ("speed it up", "SPEED", FASTER),
    ("make it faster", "SPEED", FASTER),
    ("increase playback speed", "SPEED", FASTER),
    ("set the speed to 1.75", "SPEED", rate(1.75)),
    ("play at normal speed", "SPEED", rate(1.0)),
    ("can you slow it down a little", "SPEED", SLOWER),
    ("volume up a bit", "VOLUME", LOUDER),
    ("turn the volume down", "VOLUME", QUIETER),
    ("it's too quiet", "VOLUME", LOUDER),
    ("set volume to 70", "VOLUME", vol(70)),
    ("mute please", "VOLUME", MUTE),
    ("okay thanks", "STOP_SPEAKING", STOP),
    ("that's all", "STOP_SPEAKING", STOP),
    ("stop reading", "STOP_SPEAKING", STOP),
    ("no need", "STOP_SPEAKING", STOP),
    ("video rok do", "PAUSE", PAUSE),
    ("thoda ruk jao", "PAUSE", PAUSE),
    ("ek sec", "PAUSE", PAUSE),
    ("ab chalao", "PLAY", PLAY),
    ("video start karo", "PLAY", PLAY),
    ("20 second peeche le jao", "SEEK_BACK", back(20)),
    ("thoda sa peeche", "SEEK_BACK", back(10)),
    ("ek minute pehle wala dikhao", "SEEK_BACK", back(60)),
    ("30 second aage badha do", "SEEK_FORWARD", fwd(30)),
    ("12 minute pe le chalo", "SEEK_ABSOLUTE", to(720)),
    ("shuru se dobara chalao", "SEEK_ABSOLUTE", RESTART),
    ("last mein jao", "SEEK_ABSOLUTE", END),
    ("wapas wahi pe jao", "SEEK_ABSOLUTE", PREV),
    ("fir se bolo", "REPLAY", replay()),
    ("ek baar aur sunao", "REPLAY", replay()),
    ("speed thodi badhao", "SPEED", FASTER),
    ("speed thoda kam karo", "SPEED", SLOWER),
    ("awaaz thodi badhao", "VOLUME", LOUDER),
    ("awaaz thoda kam karo", "VOLUME", QUIETER),
    ("bas ho gaya", "STOP_SPEAKING", STOP),
    ("theek hai samajh gaya", "STOP_SPEAKING", STOP),
    ("achha ruko", "PAUSE", PAUSE),
    ("mujhe 10 second peeche jana hai", "SEEK_BACK", back(10)),
    ("रोक दीजिए", "PAUSE", PAUSE),
    ("चला दीजिए", "PLAY", PLAY),
    ("थोड़ा पीछे कर दो", "SEEK_BACK", back(10)),
    ("दस सेकंड पीछे कर दीजिए", "SEEK_BACK", back(10)),
    ("पाँच सेकंड आगे", "SEEK_FORWARD", fwd(5)),
    ("आधे वीडियो पर ले चलो", "SEEK_ABSOLUTE", frac(0.5)),
    ("स्पीड थोड़ी कम कर दो", "SPEED", SLOWER),
    ("आवाज़ थोड़ी बढ़ा दो", "VOLUME", LOUDER),
    ("आवाज़ बहुत कम है", "VOLUME", LOUDER),
    ("चुप रहो", "STOP_SPEAKING", STOP),
    ("ठीक है धन्यवाद", "STOP_SPEAKING", STOP),
    ("ये वाला हिस्सा फिर से दिखाओ", "REPLAY", replay()),
    ("क्या आप थोड़ा पीछे जा सकते हैं", "SEEK_BACK", back(10)),
    ("why does he keep going back to this example", "ASK", None),
    ("is the speed of the algorithm important", "ASK", None),
    ("what is volume rendering", "ASK", None),
    ("how do we play this game", "ASK", None),
    ("ye skip kyun kiya", "ASK", None),
    # round 2
    ("could you stop the video", "PAUSE", PAUSE),
    ("pause right there", "PAUSE", PAUSE),
    ("freeze it", "PAUSE", PAUSE),
    ("hit play", "PLAY", PLAY),
    ("continue playing", "PLAY", PLAY),
    ("let it play", "PLAY", PLAY),
    ("rewind twenty seconds", "SEEK_BACK", back(20)),
    ("go back by a minute", "SEEK_BACK", back(60)),
    ("rewind 45 seconds", "SEEK_BACK", back(45)),
    ("move back a little", "SEEK_BACK", back(10)),
    ("go back 2 and a half minutes", "SEEK_BACK", back(150)),
    ("skip ahead by 10 seconds", "SEEK_FORWARD", fwd(10)),
    ("jump ahead one minute", "SEEK_FORWARD", fwd(60)),
    ("skip 5 minutes", "SEEK_FORWARD", fwd(300)),
    ("take me to 20:15", "SEEK_ABSOLUTE", to(1215)),
    ("jump to minute 45", "SEEK_ABSOLUTE", to(2700)),
    ("go to 3 minutes", "SEEK_ABSOLUTE", to(180)),
    ("restart from the beginning", "SEEK_ABSOLUTE", RESTART),
    ("go to the very end", "SEEK_ABSOLUTE", END),
    ("go back to where we were", "SEEK_ABSOLUTE", PREV),
    ("replay that", "REPLAY", replay()),
    ("repeat the last 20 seconds", "REPLAY", replay(20)),
    ("I missed what he said", "REPLAY", replay()),
    ("slow it down", "SPEED", SLOWER),
    ("make it slower", "SPEED", SLOWER),
    ("play at 1.25 speed", "SPEED", rate(1.25)),
    ("set playback speed to 2", "SPEED", rate(2.0)),
    ("normal speed please", "SPEED", rate(1.0)),
    ("a little louder please", "VOLUME", LOUDER),
    ("lower the sound", "VOLUME", QUIETER),
    ("turn up the volume", "VOLUME", LOUDER),
    ("volume to 40 percent", "VOLUME", vol(40)),
    ("okay that's enough", "STOP_SPEAKING", STOP),
    ("thanks got it", "STOP_SPEAKING", STOP),
    ("video ko pause karo", "PAUSE", PAUSE),
    ("ruk ja", "PAUSE", PAUSE),
    ("video ko chalu karo", "PLAY", PLAY),
    ("5 second peeche karo", "SEEK_BACK", back(5)),
    ("do minute peeche le jao", "SEEK_BACK", back(120)),
    ("thoda aage badha do", "SEEK_FORWARD", fwd(10)),
    ("10 minute pe jao", "SEEK_ABSOLUTE", to(600)),
    ("shuru mein le chalo", "SEEK_ABSOLUTE", START),
    ("pichla part phir se chalao", "REPLAY", replay()),
    ("speed ko 1.25 karo", "SPEED", rate(1.25)),
    ("thoda dheere chalao", "SPEED", SLOWER),
    ("volume thoda badha do", "VOLUME", LOUDER),
    ("awaaz band kar do", "VOLUME", MUTE),
    ("theek hai bas", "STOP_SPEAKING", STOP),
    ("वीडियो पॉज़ कर दो", "PAUSE", PAUSE),
    ("रुक जाइए", "PAUSE", PAUSE),
    ("चालू कर दो", "PLAY", PLAY),
    ("पंद्रह सेकंड पीछे जाओ", "SEEK_BACK", back(15)),
    ("तीस सेकंड आगे बढ़ाओ", "SEEK_FORWARD", fwd(30)),
    ("तीन मिनट पर जाओ", "SEEK_ABSOLUTE", to(180)),
    ("शुरुआत में ले चलो", "SEEK_ABSOLUTE", START),
    ("आखिरी हिस्से पर जाओ", "SEEK_ABSOLUTE", END),
    ("फिर से चलाओ", "REPLAY", replay()),
    ("स्पीड नॉर्मल कर दो", "SPEED", rate(1.0)),
    ("थोड़ा धीरे करो", "SPEED", SLOWER),
    ("आवाज़ थोड़ी कम करो", "VOLUME", QUIETER),
    ("आवाज़ बंद कर दो", "VOLUME", MUTE),
    ("बस हो गया", "STOP_SPEAKING", STOP),
    ("what happens when we pause the training", "ASK", None),
    ("why is it called fast fourier transform", "ASK", None),
    ("how much volume of data", "ASK", None),
    ("is it okay to skip this step", "ASK", None),
    ("iska speed kitna hai", "ASK", None),
    ("ye peeche wala concept kya hai", "ASK", None),
    ("don't go back", "OOS", None),
    ("mat ruko", "PLAY", PLAY),
    # traps found while fixing round 2
    ("shuru mein kya bataya tha", "ASK", None),
    ("kya aap video rok sakte hai", "PAUSE", PAUSE),
]

CASES: list[tuple[str, str, Action]] = EN + HINGLISH + HINDI + SLOW_PATH + PRECISION + HELDOUT
GROUPS: dict[str, list[tuple[str, str, Action]]] = {
    "en": EN,
    "hinglish": HINGLISH,
    "hindi": HINDI,
    "slow_path": SLOW_PATH,
    "precision": PRECISION,
    "heldout": HELDOUT,
}
